### ISSUE TITLE
A question when running PAT

### ISSUE THREAD

**Issue by youyou0805** [humansensinglab/PATMAT#1]
Hello,
Thanks for the excellent code, I have modified the parameters in paths_config.py file to set my local paths. However, when I run the command ‘python PAT/scripts/run_pat.py’, my output folder just has embeddings, as shown in the following figure:
![QQ图片20240104114700](https://github.com/humansensinglab/PATMAT/assets/65598635/227b208e-8340-4507-8b12-68ea5765e6a7)
![QQ图片20240104114655](https://github.com/humansensinglab/PATMAT/assets/65598635/88cdd2b3-f01a-44dd-ae2a-9c07992d4816)

Could you help me identify where the problem might be occurring? I'm unable to find what step I may be missing.

Please let me know if you need any other details from my end. Your help is greatly appreciated!

**Comment by sam-motamed** [comment]
Hi @youyou0805 parts of the directory names / data categories (e.g., p1, p2, p3 ...) were hardcoded and I still have not gotten around in fixing those. What do your input files and their names look like when you are running PAT?

**Comment by sam-motamed** [comment]
@youyou0805 I see, please have a look at lines 185 - 225 in multi_id_coach.py. The purpose for this naming convention is to deal with the lighting issue mentioned in Figure 3 of the paper. A quick workaround would be naming your 7 files the following: p1_1.png, ..., p1_7.png. Let me know if anything further comes up

**Comment by youyou0805** [comment]
@sam-motamed Thanks for the info. I modified the filenames, but I have encountered the following additional issue after that:
![QQ图片20240105144141](https://github.com/humansensinglab/PATMAT/assets/65598635/1712971c-3f60-4d40-b3be-11c5989f836f)
I tried adjusting the parameters but it didn't work.
I also want to ask what this file "segmentation/3.png" referred to in this line of code in the base_coach.py file is?
https://github.com/humansensinglab/PATMAT/blob/db926267e260681ef09384da3c2449c0997c36b6/PAT/training/coaches/base_coach.py#L24

**Comment by alasokolova** [comment]
Hi @youyou0805,
have you succeeded in solving this issue and running the code?
I am trying to run `run_pat.py`, too, but don't understand, where this segmentation mask should come from?
And where do embeddings (from your first comment) come from?


@sam-motamed Could you please share a small sample dataset which your code could run with?

**Comment by sam-motamed** [comment]
Sorry I had missed @youyou0805's last comment. Allow me some time and I will get back to you @alasokolova

**Comment by alasokolova** [comment]
Hey @sam-motamed!
Are there any updates? I will still be very happy if you share a data sample so that I can run the code. Or give a small explanation, where the segmentation and embeddings should come from :)

**Comment by youyou0805** [comment]
> Hey @sam-motamed! Are there any updates? I will still be very happy if you share a data sample so that I can run the code. Or give a small explanation, where the segmentation and embeddings should come from :)

I apologize, but there has been no progress so far. To this point, I still have not been able to run it successfully. If I remember correctly, the embedding folder was generated after running the command python PAT/scripts/run_pat.py. I'm unsure of the source and purpose of the segmentation folder. When running it, I commented out all the code related to segmentation. The data I used was some random photos of Taylor Swift that I found online, which I then cropped and aligned.

**Comment by alasokolova** [comment]
> > Hey @sam-motamed! Are there any updates? I will still be very happy if you share a data sample so that I can run the code. Or give a small explanation, where the segmentation and embeddings should come from :)
> 
> I apologize, but there has been no progress so far. To this point, I still have not been able to run it successfully. If I remember correctly, the embedding folder was generated after running the command python PAT/scripts/run_pat.py. I'm unsure of the source and purpose of the segmentation folder. When running it, I commented out all the code related to segmentation. The data I used was some random photos of Taylor Swift that I found online, which I then cropped and aligned.

Sorry, I mistagged you instead of @sam-motamed .
But anyway, thanks for reply! I tried to comment everything that concerns segmentation, as well, but at some point, I faced that some segmentation mask is needed in the code, and I have no idea where to get it.

**Comment by sam-motamed** [comment]
@youyou0805 @alasokolova sorry I have been quite occupied with other works and have not had the chance to look into this. If your only issue is the segmentation masks, I believe you can generate random binary masks during your tuning. I will do my best to look into this this coming week

**Comment by alasokolova** [comment]
> I believe you can generate random binary masks during your tuning.

I have tried and overcome this issue, thanks!

But then I face further issues: you have the p1,p2,p3,p4, glasses and sunglasses samples, and also separated celeb ones.
What should be the difference if I want to fine-tune the model on my own dataset?
Which samples should be considered as "celeb"?

**Comment by sam-motamed** [comment]
@alasokolova celeb here is the dataset that is used to regularize your tuning. it can have a few images that are of different people that aren't the person you are tuning the model for. You do not need to have all of p1 - p4 groups of images. The most important is to separate the glasses vs non-glasses so you could end up with only two groups p1 and p2

**Comment by alasokolova** [comment]
Ok, so p1 and p2 are images of the target person with and without glasses and celeb contains images of some other people, right? thank you!

**Comment by sam-motamed** [comment]
@alasokolova yes, unless your target person has no images with glasses / sunglasses in which case you will just have one group (p1). Thanks for pointing this out I must have uploaded my internal copy of the code. I will fix these soon but I hope this solves your issue for now

**Comment by youyou0805** [comment]
Hi! @alasokolova 
When running the command python PAT/scripts/run_pat.py, did you encounter the following issue in line 417 of multi_id_coach.py? 
![image](https://github.com/humansensinglab/PATMAT/assets/65598635/33dc96fe-96b1-4335-8b19-7d2a8b8c8cfa)
TypeError: forward() takes 2 positional arguments but 4 were given.
I am still troubled by this issue, and I have already modified the path for the mask.

**Comment by alasokolova** [comment]
It seems quite strange, since self.G.synthesis is from SynthesisNet class and its forward function is supposed to take all these arguments. I have not faced such an issue.

**Comment by youyou0805** [comment]
> It seems quite strange, since self.G.synthesis is from SynthesisNet class and its forward function is supposed to take all these arguments. I have not faced such an issue.

Ok, thank you very much for your response.

**Comment by alasokolova** [comment]
Hi @sam-motamed!
I managed to run both steps, thank you for your explanations!
I have one more question concerning MAT.
During both PAT training and MAT inference I run G.synthesis, but it seems that the model is not the same as SynthesisNet implemented in mat.py. Right? I see that some internal code is running rather than mat.py. And when I try to initialize the generator by "load_state_dict" instead of just loading the pickled checkpoint, I get a bit different result (at least, the mask is a bit visible as there is no poisson blending). Am I right?
Is the poisson blending applied in the actual model?

**Comment by sam-motamed** [comment]
@alasokolova that is great to hear. Indeed you will discrepancies without the blending. The poisson blending was done with a post processing. it should be quite easy to do. Let me know if you need help making the blending work.

**Comment by alasokolova** [comment]
Got it, thanks!
Are there any other differences except the blending?

**Comment by alasokolova** [comment]
And one more question, @sam-motamed  :)
How are the pre-calculated pivots and clusters are used for PAT training?
First, it seems that the clusters consist of equal elements.
Second, while training only the [first element](https://github.com/humansensinglab/PATMAT/blob/f8876b29fff5f627e582310fda631cf900faf5c4/PAT/training/coaches/multi_id_coach.py#L394) yielded by dataloader is used, the cluster information is ignored, the pivot is calculated from random z_sample. Am I right?

**Comment by alasokolova** [comment]
Hey @sam-motamed !
Seems like I managed to run PATMAT, thank you so much for your help!
I am also trying to run [another amazing work](https://github.com/AtlantixJJ/PVA-CelebAHQ-IDI) of yours and your colleagues. I have a [question](https://github.com/AtlantixJJ/PVA-CelebAHQ-IDI/issues/2) concerning the application of the approach to custom data, could you or your co-authors please help me?

Thank you in advance!

**Comment by sam-motamed** [comment]
That is great to hear @alasokolova. I will ping the first author to get back to you on your issue
